version: '3.9'

services:
  nuxt:
    container_name: nuxt
    build: infra/docker/nuxt
    volumes:
      - ./front:/front:cached
      - nuxt_node_modules:/front/node_modules
    ports:
      - "80:3000"
      - "24678:24678" # ホットリロード用
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=80
      - CHOKIDAR_USEPOLLING=true
#    command: sh -c "yarn && yarn dev"
volumes:
  nuxt_node_modules:
